In [1]:
import numpy as np
import pandas as pd

In [2]:
#### Train Data 

data1=pd.read_csv('../data/source_data/water_solubility_data.csv') # Dataset(A) with StdInChIKey dataset A
data2=pd.read_csv('../data/source_data/data_paper.csv',encoding='latin1') # (B)  # Dataset with Standard InChIKey and CAS_Number
data3 = pd.read_excel('../data/source_data/Supplementary_data.xlsx')#  (C) # Dataset with InChIKey
data4=pd.read_csv('../data/source_data/dataset-not-FA.csv') # (D) # Dataset with InChIKey

### Test data 
test_set=pd.read_csv('../data/source_data/dataset1-E.csv')

In [3]:
data1

,StdInChIKey,Smiles,LogS,Unnamed: 3,error,T,Source,REF1,REF2,REF3,REF4,REF5
0,AAEVYOVXGOFMJO-UHFFFAOYSA-N,S(C)c1nc(NC(C)C)nc(NC(C)C)n1,-4.10000,-3.99,-0.11,NaN,ONSchallenge,http://dx.doi.org/10.1021/ci800406y,NaN,NaN,NaN,NaN
1,ABICJYZKIYUWEE-UHFFFAOYSA-N,O=[N+]([O-])C1C(=O)NC(=O)NC1=O,-2.28000,-1.77,-0.51,NaN,ONSchallenge,http://dx.doi.org/10.1021/ci800406y,NaN,NaN,NaN,NaN
2,ADIMAYPTOBDMTL-UHFFFAOYSA-N,Clc1cc2C(=NC(O)C(=O)Nc2cc1)c1ccccc1,-3.95000,-3.90,-0.05,NaN,ONSchallenge,http://dx.doi.org/10.1021/ci800406y,NaN,NaN,NaN,NaN
3,AEXMKKGTQYQZCS-UHFFFAOYSA-N,C(CC)(CC)(C)C,-4.23000,-4.27,0.04,NaN,ONSchallenge,http://dx.doi.org/10.1021/ci800406y,NaN,NaN,NaN,NaN
4,AFFLGGQVNFXPEV-UHFFFAOYSA-N,C(=C)CCCCCCCC,-5.51000,-5.49,-0.02,NaN,ONSchallenge,http://dx.doi.org/10.1021/ci800406y,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
895,ZXVONLUNISGICL-UHFFFAOYSA-N,O=[N+]([O-])c1c(O)c(C)cc([N+](=O)[O-])c1,-1.46000,NaN,NaN,NaN,ONSchallenge,http://dx.doi.org/10.1021/ci800406y,NaN,NaN,NaN,NaN
896,ZYJPUMXJBDHSIF-NSHDSACASA-N,O=C(OC(C)(C)C)N[C@H](C(=O)O)Cc1ccccc1,-2.15490,NaN,NaN,NaN,ONSchallenge,http://onschallenge.wikispaces.com/Exp194,NaN,NaN,NaN,NaN
897,ZZLCFHIKESPLTH-UHFFFAOYSA-N,Cc1ccc(c2ccccc2)cc1,-4.62000,NaN,NaN,NaN,ONSchallenge,http://dx.doi.org/10.1021/ci800406y,NaN,NaN,NaN,NaN
898,ZZORFUFYDOWNEF-UHFFFAOYSA-N,S(=O)(=O)(Nc1nc(OC)nc(OC)c1)c1ccc(N)cc1,-2.96000,NaN,NaN,NaN,ONSchallenge,http://dx.doi.org/10.1021/ci800406y,NaN,NaN,NaN,NaN
899,ZZUFCTLCJUWOSV-UHFFFAOYSA-N,Clc1c(S(=O)(=O)N)cc(C(=O)O)c(NCc2occc2)c1,-3.80528,NaN,NaN,NaN,ONSchallenge,NaN,NaN,NaN,NaN,NaN

In [4]:
# Standardize column names for consistency
data1.rename(columns={"Smiles": "SMILES", "StdInChIKey": "InChIKey"}, inplace=True)
data2.rename(columns={"Standard InChIKey": "InChIKey", "CAS Number": "CAS"}, inplace=True)
data3.rename(columns={"logS":"LogS"},inplace=True) 
data4.rename(columns={"Solubility":"LogS"},inplace=True)
test_set.rename(columns={"Solubility":"LogS"},inplace=True)
# Assign unique IDs to each dataset
data1.insert(0, 'C_ID', ['A-' + str(i + 1) for i in range(len(data1))])
data2.insert(0, 'C_ID', ['B-' + str(i + 1) for i in range(len(data2))])
data3.insert(0, 'C_ID', ['C-' + str(i + 1) for i in range(len(data3))])
data4.insert(0, 'C_ID', ['D-' + str(i + 1) for i in range(len(data4))])
test_set.insert(0, 'C_ID', ['E-' + str(i + 1) for i in range(len(test_set))])

# Include CAS Number wherever available
# If a dataset does not have CAS, add it as an empty column for consistency
if "CAS" not in data1.columns:
    data1["CAS"] = None
if "CAS" not in data2.columns:
    data2["CAS"] = None
if "CAS" not in data3.columns:
    data3["CAS"] = None    
if "CAS" not in data4.columns:
    data4["CAS"] = None
if "CAS" not in test_set.columns:
    test_set["CAS"] = None
if "Name" not in data1.columns:
    data1["Name"] = None
if "Name" not in data2.columns:
    data2["Name"] = None    
if "Name" not in data3.columns:
    data3["Name"] = None
if "Name" not in data4.columns:
    data4["Name"] = None
if "Name" not in test_set.columns:
    test_set["Name"] = None
# Select relevant columns
data1 = data1[['C_ID', 'Name','InChIKey', 'SMILES', 'CAS', 'LogS']]
data2 = data2[['C_ID','Name', 'InChIKey', 'SMILES', 'CAS', 'LogS']]
data3 = data3[['C_ID','Name', 'InChIKey', 'SMILES', 'CAS', 'LogS']]
data4 = data4[['C_ID', 'Name','InChIKey', 'SMILES', 'CAS', 'LogS']]
test_set = test_set[['C_ID','Name','InChIKey', 'SMILES', 'CAS', 'LogS', ]]

In [5]:
### Size of each dataset 
print(data1.shape)
print(data2.shape)
print(data3.shape)
print(data4.shape)
print(test_set.shape)

(900, 6)
(11862, 6)
(9943, 6)
(6154, 6)
(1291, 6)

In [6]:
### Merging the train dataset to one dataframe 
frames = [data1,data2,data3,data4]
train_set = pd.concat(frames)

### Size of the train and test dataset before preprocess....
print('Size of the train dataset :',len(train_set))
print('Size of the test dataset :',len(test_set))

Size of the train dataset : 28859
Size of the test dataset : 1291

In [7]:
train_set

,C_ID,Name,InChIKey,SMILES,CAS,LogS
0,A-1,None,AAEVYOVXGOFMJO-UHFFFAOYSA-N,S(C)c1nc(NC(C)C)nc(NC(C)C)n1,None,-4.10
1,A-2,None,ABICJYZKIYUWEE-UHFFFAOYSA-N,O=[N+]([O-])C1C(=O)NC(=O)NC1=O,None,-2.28
2,A-3,None,ADIMAYPTOBDMTL-UHFFFAOYSA-N,Clc1cc2C(=NC(O)C(=O)Nc2cc1)c1ccccc1,None,-3.95
3,A-4,None,AEXMKKGTQYQZCS-UHFFFAOYSA-N,C(CC)(CC)(C)C,None,-4.23
4,A-5,None,AFFLGGQVNFXPEV-UHFFFAOYSA-N,C(=C)CCCCCCCC,None,-5.51
...,...,...,...,...,...,...
6149,D-6150,b-Endosulfan,RDYMFSUJUZBWLH-UHFFFAOYSA-N,O=S1OCC2C(CO1)C1(Cl)C(Cl)=C(Cl)C2(Cl)C1(Cl)Cl,None,-6.08
6150,D-6151,Parathion,LCCNCVORNKJIRZ-UHFFFAOYSA-N,CCOP(=S)(OCC)OC1=CC=C(C=C1)[N+](=O)[O-],None,-4.29
6151,D-6152,Pebulate,SGEJQUSYQTVSIU-UHFFFAOYSA-N,CCCCN(CC)C(=O)SCCC,None,-3.41
6152,D-6153,Perthane,QFMDFTQOJHFVNR-UHFFFAOYSA-N,CCC1=CC=C(C(C2=CC=C(CC)C=C2)C(Cl)Cl)C=C1,None,-7.04
6153,D-6154,Prasterone,FMGSKLZLMKYGDP-UHFFFAOYSA-N,CC12CCC3C(CC=C4CC(O)CCC43C)C1CCC2=O,None,-4.01

In [8]:
train_set.reset_index(drop=True)
test_set.reset_index(drop=True)

,C_ID,Name,InChIKey,SMILES,CAS,LogS
0,E-1,n-pentane,OFBQJSOFQDEBGM-UHFFFAOYSA-N,CCCCC,None,-3.18
1,E-2,cyclopentane,RGSFGYAAUTVSQA-UHFFFAOYSA-N,C1CCCC1,None,-2.64
2,E-3,n-hexane,VLKZOEOYAKHREP-UHFFFAOYSA-N,CCCCCC,None,-3.84
3,E-4,2-methylpentane,AFABGHUZZDYHJO-UHFFFAOYSA-N,CCCC(C)C,None,-3.74
4,E-5,"2,2-dimethylbutane",HNRMPXKDFBEGFZ-UHFFFAOYSA-N,CCC(C)(C)C,None,-3.55
...,...,...,...,...,...,...
1286,E-1287,malathion,JXSJBGJIGXNWCI-UHFFFAOYSA-N,CCOC(=O)CC(SP(=S)(OC)OC)C(=O)OCC,None,-3.37
1287,E-1288,chlorpyriphos,SBPBAQFWLVIOKP-UHFFFAOYSA-N,CCOP(=S)(OCC)Oc1nc(Cl)c(Cl)cc1Cl,None,-5.49
1288,E-1289,prostaglandin_E2,XEYBRNLFEZDVAW-UHFFFAOYSA-N,CCCCCC(O)C=CC1C(O)CC(=O)C1CC=CCCCC(=O)O,None,-2.47
1289,E-1290,"p,p'-DDT",YVGGHNCTFXOJCH-UHFFFAOYSA-N,c(ccc(c1)Cl)(c1)C(c(ccc(c2)Cl)c2)C(Cl)(Cl)Cl,None,-7.15
1290,E-1291,chlordane,BIWJNBZANLAXMG-UHFFFAOYSA-N,ClC1CC2C(C1Cl)C3(Cl)C(=C(Cl)C2(Cl)C3(Cl)Cl)Cl,None,-6.86

In [9]:
train_set

,C_ID,Name,InChIKey,SMILES,CAS,LogS
0,A-1,None,AAEVYOVXGOFMJO-UHFFFAOYSA-N,S(C)c1nc(NC(C)C)nc(NC(C)C)n1,None,-4.10
1,A-2,None,ABICJYZKIYUWEE-UHFFFAOYSA-N,O=[N+]([O-])C1C(=O)NC(=O)NC1=O,None,-2.28
2,A-3,None,ADIMAYPTOBDMTL-UHFFFAOYSA-N,Clc1cc2C(=NC(O)C(=O)Nc2cc1)c1ccccc1,None,-3.95
3,A-4,None,AEXMKKGTQYQZCS-UHFFFAOYSA-N,C(CC)(CC)(C)C,None,-4.23
4,A-5,None,AFFLGGQVNFXPEV-UHFFFAOYSA-N,C(=C)CCCCCCCC,None,-5.51
...,...,...,...,...,...,...
6149,D-6150,b-Endosulfan,RDYMFSUJUZBWLH-UHFFFAOYSA-N,O=S1OCC2C(CO1)C1(Cl)C(Cl)=C(Cl)C2(Cl)C1(Cl)Cl,None,-6.08
6150,D-6151,Parathion,LCCNCVORNKJIRZ-UHFFFAOYSA-N,CCOP(=S)(OCC)OC1=CC=C(C=C1)[N+](=O)[O-],None,-4.29
6151,D-6152,Pebulate,SGEJQUSYQTVSIU-UHFFFAOYSA-N,CCCCN(CC)C(=O)SCCC,None,-3.41
6152,D-6153,Perthane,QFMDFTQOJHFVNR-UHFFFAOYSA-N,CCC1=CC=C(C(C2=CC=C(CC)C=C2)C(Cl)Cl)C=C1,None,-7.04
6153,D-6154,Prasterone,FMGSKLZLMKYGDP-UHFFFAOYSA-N,CC12CCC3C(CC=C4CC(O)CCC43C)C1CCC2=O,None,-4.01

In [10]:
### In order to compare the train and test data we need to make smiles unique 
###  representation for that we have change the smiles to canonical smiles 

from rdkit.Chem import MolFromSmiles as smi2mol
from rdkit.Chem import MolToSmiles as mol2smi

## Function to create canonical smiles 
def canon(smi):
    try:
        mol=smi2mol(smi, sanitize=True)
        smi_canon=mol2smi(mol, isomericSmiles=False, canonical=True)
        return(smi_canon)
    except:
        print("ERROR")
        return(smi)

In [11]:
#### Applying function to create the column with canonical smiles.  
train_set['smiles_canon'] = [canon(smi) for smi in train_set.SMILES]
test_set['smiles_canon'] = [canon(smi) for smi in test_set.SMILES]

[10:55:46] WARNING: not removing hydrogen atom without neighbors
[10:55:46] WARNING: not removing hydrogen atom without neighbors
[10:55:46] WARNING: not removing hydrogen atom without neighbors
[10:55:46] WARNING: not removing hydrogen atom without neighbors
[10:55:46] WARNING: not removing hydrogen atom without neighbors
[10:55:46] WARNING: not removing hydrogen atom without neighbors
[10:55:46] WARNING: not removing hydrogen atom without neighbors
[10:55:46] WARNING: not removing hydrogen atom without neighbors
[10:55:46] WARNING: not removing hydrogen atom without neighbors
[10:55:46] WARNING: not removing hydrogen atom without neighbors
[10:55:46] WARNING: not removing hydrogen atom without neighbors
[10:55:46] WARNING: not removing hydrogen atom without neighbors

In [12]:
### Calculate  the occurence of  smiles in both train and test dataset....
train_set['occurence'] = train_set.groupby('smiles_canon')['smiles_canon'].transform('count')
test_set['occurence'] = test_set.groupby('smiles_canon')['smiles_canon'].transform('count')

In [13]:
### Taking out Unique smiles from the train and test dataset 
train_set1= train_set[train_set['occurence']==1]
print(train_set1.shape)
test_set1= test_set[test_set['occurence']==1]
print(test_set1.shape)

(13432, 8)
(1273, 8)

In [14]:
#### Taking out the dataframe which has duplicate smiles means more than one time occurence in the dataset ...
train_set2= train_set[train_set['occurence']>1]
print(train_set2.shape)
test_set2= test_set[test_set['occurence']>1]
print(test_set2.shape)

(15427, 8)
(18, 8)

In [15]:
grouped_df_train = train_set2.sort_values("SMILES").groupby("SMILES", sort=False).apply(lambda x: x).reset_index(drop=True)

In [16]:
grouped_df_test = test_set2.sort_values("SMILES").groupby("SMILES", sort=False).apply(lambda x: x).reset_index(drop=True)
grouped_df_test

,C_ID,Name,InChIKey,SMILES,CAS,LogS,smiles_canon,occurence
0,E-134,gamma-hexachlorocyclohexane,JLYXXMFPNIAWKQ-UHFFFAOYSA-N,C(C(C(C(C1Cl)Cl)Cl)Cl)(C1Cl)Cl,None,-4.59,ClC1C(Cl)C(Cl)C(Cl)C(Cl)C1Cl,2
1,E-1283,lindane,JLYXXMFPNIAWKQ-UHFFFAOYSA-N,C(C(C(C(C1Cl)Cl)Cl)Cl)(C1Cl)Cl,None,-4.60,ClC1C(Cl)C(Cl)C(Cl)C(Cl)C1Cl,2
2,E-402,dexamethasone,UREBDLICKHMUKA-UHFFFAOYSA-N,C1(=O)C=C2CCC3C4CC(C)C(O)(C(=O)CO)C4(C)CC(O)C3...,None,-3.64,CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C1(O...,2
3,E-414,betamethasone,UREBDLICKHMUKA-UHFFFAOYSA-N,C1=CC(=O)C=C2CCC3C4CC(C)C(O)(C(=O)CO)C4(C)CC(O...,None,-3.77,CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C1(O...,2
4,E-1225,"cis-1,2-Dimethylcyclohexane",KVZJLSYJROEPSQ-UHFFFAOYSA-N,C1C(C)C(C)CCC1,None,-4.27,CC1CCCCC1C,2
5,E-828,"trans-1,2-Dimethylcyclohexane",KVZJLSYJROEPSQ-UHFFFAOYSA-N,C1C(C)C(C)CCC1,None,-4.33,CC1CCCCC1C,2
6,E-665,hyodeoxycholic_acid,RUDATBOHQWOJDD-UHFFFAOYSA-N,C1C(O)CC2CC(O)C3C4CCC(C(C)CCC(=O)O)C4(C)CCC3C2...,None,-3.82,CC(CCC(=O)O)C1CCC2C3C(O)CC4CC(O)CCC4(C)C3CCC12C,2
7,E-403,hydrocortisone_acetate,ITRJWOMZKQRYTA-UHFFFAOYSA-N,CC(=O)OCC(=O)C3(O)CCC4C2CCC1=CC(=O)CCC1(C)C2C(...,None,-4.30,CC(=O)OCC(=O)C1(O)CCC2C3CCC4=CC(=O)CCC4(C)C3C(...,2
8,E-1004,Cortisone_Acetate,ITRJWOMZKQRYTA-UHFFFAOYSA-N,CC(=O)OCC(=O)C3(O)CCC4C2CCC1=CC(=O)CCC1(C)C2C(...,None,-4.00,CC(=O)OCC(=O)C1(O)CCC2C3CCC4=CC(=O)CCC4(C)C3C(...,2
9,E-257,"2,3-dimethyl-3-pentanol",RFZHJHSNHYIRNE-UHFFFAOYSA-N,CC(C)C(C)(O)CC,None,-0.85,CCC(C)(O)C(C)C,2
10,E-1082,"2,4-dimethyl-3-pentanol",RFZHJHSNHYIRNE-UHFFFAOYSA-N,CC(C)C(O)(C)CC,None,-1.22,CCC(C)(O)C(C)C,2
11,E-666,chenodeoxycholic_acid,RUDATBOHQWOJDD-UHFFFAOYSA-N,CC(CCC(O)=O)C3CCC4C2C(O)CC1CC(O)CCC1(C)C2CCC34C,None,-3.64,CC(CCC(=O)O)C1CCC2C3C(O)CC4CC(O)CCC4(C)C3CCC12C,2
12,E-544,kasugamycin,OWNAXTAAAQTBSP-UHFFFAOYSA-N,CN(C)C(=O)Nc1cccc(OC(=O)NC(C)(C)C)c1,None,-2.93,CN(C)C(=O)Nc1cccc(OC(=O)NC(C)(C)C)c1,2
13,E-944,Karbutilate,OWNAXTAAAQTBSP-UHFFFAOYSA-N,CN(C)C(=O)Nc1cccc(OC(=O)NC(C)(C)C)c1,None,-2.93,CN(C)C(=O)Nc1cccc(OC(=O)NC(C)(C)C)c1,2
14,E-1128,dieldrin,DFBKLUNHFCTMDC-UHFFFAOYSA-N,ClC4=C(Cl)C5(Cl)C3C1CC(C2OC12)C3C4(Cl)C5(Cl)Cl,None,-6.29,ClC1=C(Cl)C2(Cl)C3C4CC(C5OC45)C3C1(Cl)C2(Cl)Cl,2
15,E-145,endrin,DFBKLUNHFCTMDC-UHFFFAOYSA-N,ClC4=C(Cl)C5(Cl)C3C1CC(C2OC12)C3C4(Cl)C5(Cl)Cl,None,-6.18,ClC1=C(Cl)C2(Cl)C3C4CC(C5OC45)C3C1(Cl)C2(Cl)Cl,2
16,E-973,Hyoscyamine,RKUNBYITZUJHSG-UHFFFAOYSA-N,O=C(OC(CC(N(C1C2)C)C2)C1)C(c(cccc3)c3)CO,None,-1.91,CN1C2CCC1CC(OC(=O)C(CO)c1ccccc1)C2,2
17,E-1141,atropine,RKUNBYITZUJHSG-UHFFFAOYSA-N,O=C(OC(CC(N(C1C2)C)C2)C1)C(c(cccc3)c3)CO,None,-2.12,CN1C2CCC1CC(OC(=O)C(CO)c1ccccc1)C2,2

In [38]:
### Not used
#Extract duplicate rows
id1 = train_set2["smiles_canon"]
train_set2=train_set2[id1.isin(id1[id1.duplicated()])].sort_values("smiles_canon")
id2 = test_set2["smiles_canon"]
test_set2=test_set2[id2.isin(id2[id2.duplicated()])].sort_values("smiles_canon")

In [17]:
print(train_set2.shape)
print(test_set2.shape)

(15427, 8)
(18, 8)

In [18]:
train_set2.reset_index(drop=True)
test_set2.reset_index(drop=True)

,C_ID,Name,InChIKey,SMILES,CAS,LogS,smiles_canon,occurence
0,E-134,gamma-hexachlorocyclohexane,JLYXXMFPNIAWKQ-UHFFFAOYSA-N,C(C(C(C(C1Cl)Cl)Cl)Cl)(C1Cl)Cl,None,-4.59,ClC1C(Cl)C(Cl)C(Cl)C(Cl)C1Cl,2
1,E-145,endrin,DFBKLUNHFCTMDC-UHFFFAOYSA-N,ClC4=C(Cl)C5(Cl)C3C1CC(C2OC12)C3C4(Cl)C5(Cl)Cl,None,-6.18,ClC1=C(Cl)C2(Cl)C3C4CC(C5OC45)C3C1(Cl)C2(Cl)Cl,2
2,E-257,"2,3-dimethyl-3-pentanol",RFZHJHSNHYIRNE-UHFFFAOYSA-N,CC(C)C(C)(O)CC,None,-0.85,CCC(C)(O)C(C)C,2
3,E-402,dexamethasone,UREBDLICKHMUKA-UHFFFAOYSA-N,C1(=O)C=C2CCC3C4CC(C)C(O)(C(=O)CO)C4(C)CC(O)C3...,None,-3.64,CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C1(O...,2
4,E-403,hydrocortisone_acetate,ITRJWOMZKQRYTA-UHFFFAOYSA-N,CC(=O)OCC(=O)C3(O)CCC4C2CCC1=CC(=O)CCC1(C)C2C(...,None,-4.30,CC(=O)OCC(=O)C1(O)CCC2C3CCC4=CC(=O)CCC4(C)C3C(...,2
5,E-414,betamethasone,UREBDLICKHMUKA-UHFFFAOYSA-N,C1=CC(=O)C=C2CCC3C4CC(C)C(O)(C(=O)CO)C4(C)CC(O...,None,-3.77,CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C1(O...,2
6,E-544,kasugamycin,OWNAXTAAAQTBSP-UHFFFAOYSA-N,CN(C)C(=O)Nc1cccc(OC(=O)NC(C)(C)C)c1,None,-2.93,CN(C)C(=O)Nc1cccc(OC(=O)NC(C)(C)C)c1,2
7,E-665,hyodeoxycholic_acid,RUDATBOHQWOJDD-UHFFFAOYSA-N,C1C(O)CC2CC(O)C3C4CCC(C(C)CCC(=O)O)C4(C)CCC3C2...,None,-3.82,CC(CCC(=O)O)C1CCC2C3C(O)CC4CC(O)CCC4(C)C3CCC12C,2
8,E-666,chenodeoxycholic_acid,RUDATBOHQWOJDD-UHFFFAOYSA-N,CC(CCC(O)=O)C3CCC4C2C(O)CC1CC(O)CCC1(C)C2CCC34C,None,-3.64,CC(CCC(=O)O)C1CCC2C3C(O)CC4CC(O)CCC4(C)C3CCC12C,2
9,E-828,"trans-1,2-Dimethylcyclohexane",KVZJLSYJROEPSQ-UHFFFAOYSA-N,C1C(C)C(C)CCC1,None,-4.33,CC1CCCCC1C,2
10,E-944,Karbutilate,OWNAXTAAAQTBSP-UHFFFAOYSA-N,CN(C)C(=O)Nc1cccc(OC(=O)NC(C)(C)C)c1,None,-2.93,CN(C)C(=O)Nc1cccc(OC(=O)NC(C)(C)C)c1,2
11,E-973,Hyoscyamine,RKUNBYITZUJHSG-UHFFFAOYSA-N,O=C(OC(CC(N(C1C2)C)C2)C1)C(c(cccc3)c3)CO,None,-1.91,CN1C2CCC1CC(OC(=O)C(CO)c1ccccc1)C2,2
12,E-1004,Cortisone_Acetate,ITRJWOMZKQRYTA-UHFFFAOYSA-N,CC(=O)OCC(=O)C3(O)CCC4C2CCC1=CC(=O)CCC1(C)C2C(...,None,-4.00,CC(=O)OCC(=O)C1(O)CCC2C3CCC4=CC(=O)CCC4(C)C3C(...,2
13,E-1082,"2,4-dimethyl-3-pentanol",RFZHJHSNHYIRNE-UHFFFAOYSA-N,CC(C)C(O)(C)CC,None,-1.22,CCC(C)(O)C(C)C,2
14,E-1128,dieldrin,DFBKLUNHFCTMDC-UHFFFAOYSA-N,ClC4=C(Cl)C5(Cl)C3C1CC(C2OC12)C3C4(Cl)C5(Cl)Cl,None,-6.29,ClC1=C(Cl)C2(Cl)C3C4CC(C5OC45)C3C1(Cl)C2(Cl)Cl,2
15,E-1141,atropine,RKUNBYITZUJHSG-UHFFFAOYSA-N,O=C(OC(CC(N(C1C2)C)C2)C1)C(c(cccc3)c3)CO,None,-2.12,CN1C2CCC1CC(OC(=O)C(CO)c1ccccc1)C2,2
16,E-1225,"cis-1,2-Dimethylcyclohexane",KVZJLSYJROEPSQ-UHFFFAOYSA-N,C1C(C)C(C)CCC1,None,-4.27,CC1CCCCC1C,2
17,E-1283,lindane,JLYXXMFPNIAWKQ-UHFFFAOYSA-N,C(C(C(C(C1Cl)Cl)Cl)Cl)(C1Cl)Cl,None,-4.60,ClC1C(Cl)C(Cl)C(Cl)C(Cl)C1Cl,2

In [19]:
# Group by SMILES
grouped_train = train_set2.groupby('smiles_canon')
grouped_test = test_set2.groupby('smiles_canon')
# Filter groups where the maximum difference in solubility is less than or equal to 0.50
filtered_groups_train = grouped_train.filter(lambda x: x['LogS'].max() - x['LogS'].min() <= 0.50)
filtered_groups_test = grouped_test.filter(lambda x: x['LogS'].max() - x['LogS'].min() <= 0.50)

In [20]:
print(len(filtered_groups_train))
print(len(filtered_groups_test))

14044
18

In [21]:
### In order to eavluate to threshold followed by the dataframe we  cross check the value of difference
grouped = filtered_groups_train.groupby('smiles_canon')['LogS'].apply(lambda x: x.sort_values().tolist())

# Calculate differences in solubility within each group
diffs = grouped.apply(lambda x: [j - i for i, j in zip(x[:-1], x[1:])])

# Create a new DataFrame with SMILES, Solubility values, and differences
result = grouped.reset_index()
result.columns = ['smiles_canon', 'Solubility_Values']

# Add the differences as a new column
result['Differences'] = diffs.values

result

,smiles_canon,Solubility_Values,Differences
0,Br.CN(C)CCC=C1c2ccccc2Sc2ccc(F)cc21,"[-5.603798043, -5.603798043]",[0.0]
1,Br.Oc1ccc2c(c1)C13CCCCC1C(C2)N(CCc1ccccc1)CC3,"[-4.833904011, -4.833904011]",[0.0]
2,BrC(Br)(Br)Br,"[-3.157037902, -3.1400001, -3.14]","[0.017037801999999935, 9.999999983634211e-08]"
3,BrC(Br)Br,"[-1.911295104, -1.91, -1.91]","[0.0012951039999999914, 0.0]"
4,BrC(Br)C(Br)Br,"[-2.72, -2.710626523]",[0.009373477000000019]
...,...,...,...
5683,c1cnoc1,"[0.3827, 0.383489897]",[0.0007898970000000394]
5684,c1coc(-c2nc3ccccc3[nH]2)c1,"[-3.414031277, -3.414]",[3.127699999971867e-05]
5685,c1nc[nH]n1,"[0.788504777, 1.005834993]",[0.2173302159999999]
5686,c1ncc2[nH]cnc2n1,"[0.619390837, 0.62]",[0.0006091630000000237]
5687,c1ncc2n[nH]nc2n1,"[-0.2319, -0.2319]",[0.0]

In [22]:
### taking the mean of duplicates smiles of the train dataset 
df_grouped_train = filtered_groups_train.groupby("smiles_canon", as_index=False).agg({
    "C_ID": "first",
    "Name":"first",
    "InChIKey": "first",
    "SMILES": "first",  # Keep the first occurrence
    "smiles_canon": "first",  # Keep the first CAS number
    "LogS": "mean",  # Take the mean of solubility values
    "CAS": "first",  # Take mean if applicable
    
})

In [23]:
### taking the mean of duplicates smiles of the test dataset 
df_grouped_test = filtered_groups_test.groupby("smiles_canon", as_index=False).agg({
    "C_ID": "first",
    "Name":"first",
    "InChIKey": "first",
    "SMILES": "first",  # Keep the first occurrence
    "smiles_canon": "first",  # Keep the first CAS number
    "LogS": "mean",  # Take the mean of solubility values
    "CAS": "first",  # Take mean if applicable   
})

In [24]:
### Combining the dataframe with single entry and multiple entry matching smiles and average the solubility values 

train_set=pd.concat([train_set1, df_grouped_train], axis=0, ignore_index=True)
test_set=pd.concat([test_set1, df_grouped_test], axis=0, ignore_index=True)

In [25]:
print(train_set.shape)
print(test_set.shape)

(19120, 8)
(1282, 8)

In [26]:
### Now dropping the occurence column 
train_set = train_set.iloc[:, :-1]
test_set = test_set.iloc[:, :-1]

In [27]:
train_set

,C_ID,Name,InChIKey,SMILES,CAS,LogS,smiles_canon
0,A-51,None,BOCJQSFSGAZAPQ-UHFFFAOYSA-N,Clc1c2C(=O)c3c(C(=O)c2ccc1)cccc3,None,-5.540000,O=C1c2ccccc2C(=O)c2c(Cl)cccc21
1,A-53,None,BRBKOPJOKNSWSG-UHFFFAOYSA-N,S(=O)(=O)(N=C(N)N)c1ccc(N)cc1,None,-1.984970,NC(N)=NS(=O)(=O)c1ccc(N)cc1
2,A-55,None,BRPOVUNVTUCYNN-UHFFFAOYSA-N,Fc1c(N2C(CC)C(N)C2)cc2n(C3CC3)cc(C(=O)O)c(=O)c2c1,None,-3.912000,CCC1C(N)CN1c1cc2c(cc1F)c(=O)c(C(=O)O)cn2C1CC1
3,A-60,None,BWXSXZAIQQSFPW-UHFFFAOYSA-N,O=[N+]([O-])c1cc2C(=O)OC(CC)(CC)c2cc1,None,-3.656000,CCC1(CC)OC(=O)c2cc([N+](=O)[O-])ccc21
4,A-68,None,CAQHPYSDQFDJAL-UHFFFAOYSA-N,O=C1C(=NO)c2c(cccc2)C=C1,None,-2.937000,O=C1C=Cc2ccccc2C1=NO
...,...,...,...,...,...,...,...
19115,B-1403,ISO-OXAZOLE,CTAPFRYPJLPFDF-UHFFFAOYSA-N,C1=CON=C1,000288-14-2,0.383095,c1cnoc1
19116,B-2414,FUBERIDAZOLE,UYJUZNLFJAWNEZ-UHFFFAOYSA-N,C1=CC=C2C(=C1)NC(=N2)C3=CC=CO3,003878-19-1,-3.414016,c1coc(-c2nc3ccccc3[nH]2)c1
19117,B-7032,1H-1.2.4-Triazole,NSPMIYGKQJPBQR-UHFFFAOYSA-N,C1=NC=NN1,000288-88-0,0.897170,c1nc[nH]n1
19118,B-2548,1H-PURINE,KDCGOANMDULRCW-UHFFFAOYSA-N,C1=C2C(=NC=N1)N=CN2,000120-73-0,0.619695,c1ncc2[nH]cnc2n1
19119,B-4508,1H-1.2.3-Triazolo[4.5-d]pyrimidine,GIIGHSIIKVOWKZ-UHFFFAOYSA-N,C1=NC=NC2=NNN=C21,000273-40-5,-0.231900,c1ncc2n[nH]nc2n1

In [28]:
### Now we have all unique smiles , Now we need to make sure there should not be any 
### compound train data which match with test data 
Match_rows = pd.merge(test_set, train_set, on=['smiles_canon'], how='inner')
#mergedStuff.head()
print(len(Match_rows))

1183

In [29]:
### Finding the matching smiles in the train dataset..
cond = train_set['smiles_canon'].isin(Match_rows['smiles_canon'])

#### Dropping the smiles which is same and making dataframe with uniques smiles and no smiles same in ttrain  dataset 
train_set.drop(train_set[cond].index, inplace = True)

In [30]:
print(train_set.shape)
print(test_set.shape)

(17937, 7)
(1282, 7)

In [31]:
train_set.reset_index(drop=True)
test_set.reset_index(drop=True)

,C_ID,Name,InChIKey,SMILES,CAS,LogS,smiles_canon
0,E-1,n-pentane,OFBQJSOFQDEBGM-UHFFFAOYSA-N,CCCCC,None,-3.180,CCCCC
1,E-2,cyclopentane,RGSFGYAAUTVSQA-UHFFFAOYSA-N,C1CCCC1,None,-2.640,C1CCCC1
2,E-3,n-hexane,VLKZOEOYAKHREP-UHFFFAOYSA-N,CCCCCC,None,-3.840,CCCCCC
3,E-4,2-methylpentane,AFABGHUZZDYHJO-UHFFFAOYSA-N,CCCC(C)C,None,-3.740,CCCC(C)C
4,E-5,"2,2-dimethylbutane",HNRMPXKDFBEGFZ-UHFFFAOYSA-N,CCC(C)(C)C,None,-3.550,CCC(C)(C)C
...,...,...,...,...,...,...,...
1277,E-257,"2,3-dimethyl-3-pentanol",RFZHJHSNHYIRNE-UHFFFAOYSA-N,CC(C)C(C)(O)CC,None,-1.035,CCC(C)(O)C(C)C
1278,E-544,kasugamycin,OWNAXTAAAQTBSP-UHFFFAOYSA-N,CN(C)C(=O)Nc1cccc(OC(=O)NC(C)(C)C)c1,None,-2.930,CN(C)C(=O)Nc1cccc(OC(=O)NC(C)(C)C)c1
1279,E-973,Hyoscyamine,RKUNBYITZUJHSG-UHFFFAOYSA-N,O=C(OC(CC(N(C1C2)C)C2)C1)C(c(cccc3)c3)CO,None,-2.015,CN1C2CCC1CC(OC(=O)C(CO)c1ccccc1)C2
1280,E-145,endrin,DFBKLUNHFCTMDC-UHFFFAOYSA-N,ClC4=C(Cl)C5(Cl)C3C1CC(C2OC12)C3C4(Cl)C5(Cl)Cl,None,-6.235,ClC1=C(Cl)C2(Cl)C3C4CC(C5OC45)C3C1(Cl)C2(Cl)Cl
1281,E-134,gamma-hexachlorocyclohexane,JLYXXMFPNIAWKQ-UHFFFAOYSA-N,C(C(C(C(C1Cl)Cl)Cl)Cl)(C1Cl)Cl,None,-4.595,ClC1C(Cl)C(Cl)C(Cl)C(Cl)C1Cl

In [32]:
### Cross check in order to find that any matching smiles exist in the train dataset with test dataset
Match_rows = pd.merge(test_set, train_set, on=['smiles_canon'], how='inner')
#mergedStuff.head()
print(len(Match_rows))

0

In [33]:
train_set.reset_index(drop=True)

,C_ID,Name,InChIKey,SMILES,CAS,LogS,smiles_canon
0,A-51,None,BOCJQSFSGAZAPQ-UHFFFAOYSA-N,Clc1c2C(=O)c3c(C(=O)c2ccc1)cccc3,None,-5.540000,O=C1c2ccccc2C(=O)c2c(Cl)cccc21
1,A-53,None,BRBKOPJOKNSWSG-UHFFFAOYSA-N,S(=O)(=O)(N=C(N)N)c1ccc(N)cc1,None,-1.984970,NC(N)=NS(=O)(=O)c1ccc(N)cc1
2,A-55,None,BRPOVUNVTUCYNN-UHFFFAOYSA-N,Fc1c(N2C(CC)C(N)C2)cc2n(C3CC3)cc(C(=O)O)c(=O)c2c1,None,-3.912000,CCC1C(N)CN1c1cc2c(cc1F)c(=O)c(C(=O)O)cn2C1CC1
3,A-60,None,BWXSXZAIQQSFPW-UHFFFAOYSA-N,O=[N+]([O-])c1cc2C(=O)OC(CC)(CC)c2cc1,None,-3.656000,CCC1(CC)OC(=O)c2cc([N+](=O)[O-])ccc21
4,A-68,None,CAQHPYSDQFDJAL-UHFFFAOYSA-N,O=C1C(=NO)c2c(cccc2)C=C1,None,-2.937000,O=C1C=Cc2ccccc2C1=NO
...,...,...,...,...,...,...,...
17932,B-1403,ISO-OXAZOLE,CTAPFRYPJLPFDF-UHFFFAOYSA-N,C1=CON=C1,000288-14-2,0.383095,c1cnoc1
17933,B-2414,FUBERIDAZOLE,UYJUZNLFJAWNEZ-UHFFFAOYSA-N,C1=CC=C2C(=C1)NC(=N2)C3=CC=CO3,003878-19-1,-3.414016,c1coc(-c2nc3ccccc3[nH]2)c1
17934,B-7032,1H-1.2.4-Triazole,NSPMIYGKQJPBQR-UHFFFAOYSA-N,C1=NC=NN1,000288-88-0,0.897170,c1nc[nH]n1
17935,B-2548,1H-PURINE,KDCGOANMDULRCW-UHFFFAOYSA-N,C1=C2C(=NC=N1)N=CN2,000120-73-0,0.619695,c1ncc2[nH]cnc2n1
17936,B-4508,1H-1.2.3-Triazolo[4.5-d]pyrimidine,GIIGHSIIKVOWKZ-UHFFFAOYSA-N,C1=NC=NC2=NNN=C21,000273-40-5,-0.231900,c1ncc2n[nH]nc2n1

In [34]:
print(train_set.shape)
print(test_set.shape)

(17937, 7)
(1282, 7)

In [35]:
### Again cross check if there is any overlap 
train_smiles = set(train_set['smiles_canon'])
test_smiles = set(test_set['smiles_canon'])
overlap = train_smiles.intersection(test_smiles)

if overlap:
    print("There are overlapping smiles between the training and test datasets:")
    print(overlap)
else:
    print("No overlapping smiles between the training and test datasets.")

No overlapping smiles between the training and test datasets.

In [169]:
#### End here ....